language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-macos.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux.sh; fi
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: "b8Wg9RqYeOp5wooWh5aBy1c12sn7jm8TDM1z7A1U1LQL32HKvR/0MIgW6bWyXuHFwWO7C3tKfBS1aagKDApBQezL1G5F4foFgsQEqG/tNqCflnkdY7ZgZgC6Yvof8UmkrAZrPXV8vBO4v9tRwc/qyfCG4j5DPjBoFqEmsGex+GI="
  file:
    - "build/*.deb"
    - "build/*.rpm"
    - "build/*.dmg"
  on:
    repo: ericwa/TrenchBroom
    tags: true
